# Generated by Django 3.2.12 on 2022-02-16 23:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentorsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorSessionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('session_length', models.IntegerField(blank=True, null=True)),
                ('mentor_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='mentors.mentorsession')),
            ],
        ),
    ]
