# Generated by Django 3.2.12 on 2022-02-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_alter_mentor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='rate',
            field=models.IntegerField(default=1000),
        ),
    ]
