# Generated by Django 3.2.12 on 2022-03-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0006_auto_20220301_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
