# Generated by Django 3.2.12 on 2022-03-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0007_mentor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorsession',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
