# Generated by Django 3.2.12 on 2022-03-07 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0008_mentorsession_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
