# Generated by Django 3.2.12 on 2022-02-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(default='abc', max_length=100),
            preserve_default=False,
        ),
    ]
