# Generated by Django 3.2.12 on 2022-02-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220222_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_customer_id',
            field=models.CharField(default='123123123', max_length=100),
            preserve_default=False,
        ),
    ]
